### ISSUE TITLE
path is incorrect when only generate one type

### ISSUE THREAD

**Issue by sunwell1994** [JorisCos/LibriMix#12]
There may be such an issue in the script. 
When I just generate mix_clean,  it will not generate a noise subdir. But it still needs to weite_noise() in the noise subdir, then it will have an error due to no 'noise' path.

**Comment by JorisCos** [comment]
Thanks for reporting, I will look into it.

**Comment by jyhan03** [comment]
This problem seems hasn't been solved. I also encountered it recently.

**Comment by wslbeck** [comment]
How to solve it？I also encountered.

**Comment by JorisCos** [comment]
Related to #20
