### ISSUE TITLE
use part of train-clean-100.tar.gz

### ISSUE THREAD

**Issue by fncode246** [JorisCos/LibriMix#13]
how can i create just 10 hours mix from train-clean-100.tar.gz (instead of 100 h)

**Comment by mpariente** [comment]
Select 10% of the file list by hand in the code?

**Comment by JorisCos** [comment]
You could do either one. You can cut the csv Files with the desired length or read only a part of the cv files in the code [here](https://github.com/JorisCos/LibriMix/blob/master/scripts/create_librimix_from_metadata.py??plain=1#L78)

**Comment by jvel07** [comment]
Sure, that worked. Thanks for your reply. 
I've seen there's also a `Libri1Mix` corpus. How does one generate this one? or when can I find it?

**Comment by mpariente** [comment]
Where did you hear about Libri1Mix ?

**Comment by JorisCos** [comment]
Yes it is 
> or ir corresponds to the mix_single folders (1 speaker)?
