### ISSUE TITLE
data process

### ISSUE THREAD

**Issue by charlesXu86** [JorisCos/LibriMix#14]
Error opening 'storage_dir/wham_noise/tt/445c0204_1.7413_442c020t_-1.7413.wav': System error.
How to solve this problem？

**Comment by JorisCos** [comment]
Hello, can you post a more detailed error report please ?

**Comment by Aiga-Andrijanova** [comment]
I am having the same error. I am running on Windows 10 and I've installed all required libraries. I am running create_librimix_from_metadata.py separately. Data was downloaded with the script provided.

![image](https://user-images.githubusercontent.com/42334573/121581969-23595080-ca37-11eb-8bf1-f9605b21478c.png)
![image](https://user-images.githubusercontent.com/42334573/121582025-32d89980-ca37-11eb-8a07-606d1ed78d80.png)

**Comment by JorisCos** [comment]
Have you also installed SoX ? `conda install -c groakat sox`
Also make sure the file is actually in the right location and try open it with 
```
import soundfile as sf
_, _ =sf.read(path_to_the_file)
```
