### ISSUE TITLE
RuntimeError: Error opening……

### ISSUE THREAD

**Issue by ruanr7** [JorisCos/LibriMix#21]
I have this error when I just run this command:"./generate_librimix.sh storage_dir".The program stoped.
 How to solve this problem? And I have installed the sox. If it needs to change the code,which file should I change？
I am a beginner and sorry to bother you.o(╥﹏╥)o
<img width="925" alt="捕获" src="https://user-images.githubusercontent.com/58650301/138549509-ef0dfe5e-772d-4552-baff-58dc96862f13.PNG">

**Comment by Ashh-Z** [comment]
@wrsIt How did you get past this issue ? I am facing a similar problem.
