### ISSUE TITLE
can't generate librimix_metadata as same as you provided

### ISSUE THREAD

**Issue by Onlytwow** [JorisCos/LibriMix#23]
I run create_librimix_metadata.py to generate the file. But there are some differences between yours and mine. I don't know why. I run this script on windows10.
this is mine of libri2mix_dev-clean.csv.
![Mine](https://user-images.githubusercontent.com/46840441/142625417-c2ec93a3-d349-42f4-bd2f-21c805f4c918.JPG)
this is provided of libri2mix_dev-clean.csv .
![pro](https://user-images.githubusercontent.com/46840441/142625454-709e4e54-019a-4018-84a4-f15d2b44f5fb.JPG)

here is the command I used.
```
python create_librimix_metadata.py --librispeech_dir /f/data/LibriSpeech --librispeech_md_dir /f/LibriMix/metadata/LibriSpeech --wham_dir /f/data/wham_noise --wham_md_dir /f/LibriMix/metadata/Wham_noise --metadata_outdir /f/LibriMix/metadata/Libri2Mix_new --n_src 2
```

**Comment by JorisCos** [comment]
Sorry for the late reply. There is some randomness involved in the metadata creation. It is supposed to be seeded but It is hard to maintain reproducibility even with seeding this is why we provided the metadata. Please use the provided ones.
