### ISSUE TITLE
soundfile.LibsndfileError: Error opening,

### ISSUE THREAD

**Issue by hashirkz1** [JorisCos/LibriMix#28]
It appears that augmented files have not been generated properly
Resuming augmentation.
Change speed with factor 0.8
0it [00:00, ?it/s]
Change speed with factor 1.2
0it [00:00, ?it/s]
Directory /content/drive/MyDrive/8kdatasettrial/Libri2Mix/wav8k/max/test already exist. Files won't be overwritten
Creating mixtures and sources from /content/LibriMix/metadata/Libri2Mix/libri2mix_train-clean-100.csv in /content/drive/MyDrive/8kdatasettrial/Libri2Mix/wav8k/max/train-100
  0% 0/13900 [00:00<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/content/LibriMix/scripts/create_librimix_from_metadata.py", line 159, in process_utterance
    wham_dir)
  File "/content/LibriMix/scripts/create_librimix_from_metadata.py", line 249, in read_sources
    noise, _ = sf.read(noise_path, dtype='float32', stop=max_length)
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 286, in read
    subtype, endian, format, closefd) as f:
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/content/drive/MyDrive/8kdatasettrial/wham_noise/tr/20lo010l_0.062866_015o030q_-0.062866.wav': System error.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/LibriMix/scripts/create_librimix_from_metadata.py", line 415, in <module>
    main(args)
  File "/content/LibriMix/scripts/create_librimix_from_metadata.py", line 59, in main
    freqs, n_src, modes, types)
  File "/content/LibriMix/scripts/create_librimix_from_metadata.py", line 72, in create_librimix
    wham_dir, out_dir, modes, types)
  File "/content/LibriMix/scripts/create_librimix_from_metadata.py", line 115, in process_metadata_file
    subdirs, dir_path, subset_metadata_path, n_src)
  File "/content/LibriMix/scripts/create_librimix_from_metadata.py", line 138, in process_utterances
    chunksize=10,
  File "/usr/local/lib/python3.7/site-packages/tqdm/contrib/concurrent.py", line 130, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/usr/local/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
soundfile.LibsndfileError: Error opening '/content/drive/MyDrive/8kdatasettrial/wham_noise/tr/20lo010l_0.062866_015o030q_-0.062866.wav': System error.

**Comment by hashirkz1** [comment]
if anyone knows how to resolve these issues please let me know i have generated all the files but some files are missing in wham tt & tr.

**Comment by emanueleielo** [comment]
I have the same error, stil didn't found solution.
@hashirkz1  how much your generation require? In google colab look like is infinite, even more than 10 hours.

**Comment by hashirkz1** [comment]
> I have the same error, stil didn't found solution. @hashirkz1 how much your generation require? In google colab look like is infinite, even more than 10 hours.

i takes 2 to 3 hours for generation although it is not generated yet for me

**Comment by emanueleielo** [comment]
> > I have the same error, stil didn't found solution. @hashirkz1 how much your generation require? In google colab look like is infinite, even more than 10 hours.
> 
> 
> 
> i takes 2 to 3 hours for generation although it is not generated yet for me 

I fixed man! You should remove the version on pysound in the requirements.txt, uninstall it and install the requirements again.
If you are on colab I suggest u to restart the runtime.
I removed the 8k and max options and it looks like it finished to generate.
If you manage to generate some can you give me how much is the size of the folders?
Thanks!

**Comment by hashirkz1** [comment]
> > > I have the same error, stil didn't found solution. @hashirkz1 how much your generation require? In google colab look like is infinite, even more than 10 hours.
> > 
> > 
> > i takes 2 to 3 hours for generation although it is not generated yet for me
> 
> I fixed man! You should remove the version on pysound in the requirements.txt, uninstall it and install the requirements again. If you are on colab I suggest u to restart the runtime. I removed the 8k and max options and it looks like it finished to generate. If you manage to generate some can you give me how much is the size of the folders? Thanks!

in my case it is showing that the files are generated 100% but there is not folder naming Libri3Mix in the drive,
i am trying your method and i will let you know

**Comment by emanueleielo** [comment]
> > > > I have the same error, stil didn't found solution. @hashirkz1 how much your generation require? In google colab look like is infinite, even more than 10 hours.
> 
> > > 
> 
> > > 
> 
> > > i takes 2 to 3 hours for generation although it is not generated yet for me
> 
> > 
> 
> > I fixed man! You should remove the version on pysound in the requirements.txt, uninstall it and install the requirements again. If you are on colab I suggest u to restart the runtime. I removed the 8k and max options and it looks like it finished to generate. If you manage to generate some can you give me how much is the size of the folders? Thanks!
> 
> 
> 
> in my case it is showing that the files are generated 100% but there is not folder naming Libri3Mix in the drive,
> 
> i am trying your method and i will let you know 
> 
> 

Maybe because you generated only the Libri2Mix? It can be

**Comment by hashirkz1** [comment]
> > > > > I have the same error, stil didn't found solution. @hashirkz1 how much your generation require? In google colab look like is infinite, even more than 10 hours.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > i takes 2 to 3 hours for generation although it is not generated yet for me
> > 
> > 
> > > 
> > 
> > 
> > > I fixed man! You should remove the version on pysound in the requirements.txt, uninstall it and install the requirements again. If you are on colab I suggest u to restart the runtime. I removed the 8k and max options and it looks like it finished to generate. If you manage to generate some can you give me how much is the size of the folders? Thanks!
> > 
> > 
> > in my case it is showing that the files are generated 100% but there is not folder naming Libri3Mix in the drive,
> > i am trying your method and i will let you know
> 
> Maybe because you generated only the Libri2Mix? It can be

Have you generated all the files of the train-100 and train-360 ?

**Comment by hashirkz1** [comment]
also can you please tell me how long it took to generate all files ?
