### ISSUE TITLE
How to create Libri2Mix dataset?

### ISSUE THREAD

**Issue by xlzhou01** [JorisCos/LibriMix#29]
Hello, this is the first time I use this to create a Libri2Mix dataset and I don't know how to modify **generate_librimix.sh** script files. I've downloaded LibriSpeech and WHAM! dataset. 

![image](https://github.com/JorisCos/LibriMix/assets/145009606/58235ed9-a3fd-4bb7-b147-402d38e1bd9a)

I want to create **Libri2Mix/wav8k/min/test, Libri2Mix/wav8k/min/train-100, and Libri2Mix/wav8k/min/dev** as described in the Storage_inf.txt table in metadata.

Can you give some good implementation steps, sorry I did this in the first place.

**Comment by xlzhou01** [comment]
I researched it myself and created it.

**Comment by AvivSham** [comment]
Hi @JorisCos,
We followed the instructions in the README to create the Libri2Mix dataset, and the script was completed successfully without any errors. However, we noticed that there is no test directory under the `min` folder. Could you help clarify the steps required to create the test split? 

@xlzhou01, could you provide more details on the steps you took to generate the `test` set?

Thanks!
