### ISSUE TITLE
Generating 4 and 5 source mixtures

### ISSUE THREAD

**Issue by wenyuc55** [JorisCos/LibriMix#32]
Hi,

I'm trying to generate 4 and 5 source mixtures for training. I tried changing for n_src in 2 3; do to for n_src in 4 5; do which generates the 2 and 3 mixtures just fine but get an error that the metadata files hadn't been generated for libri4mix. Any suggestions on how I'd go about getting the script to do 4 and 5 source mixtures?
![image](https://github.com/JorisCos/LibriMix/assets/107466802/f52f7a04-f85a-4caf-9493-be4b9630dfaa)
![image](https://github.com/JorisCos/LibriMix/assets/107466802/719cc717-db97-48ed-a6ec-c8b17da4a4c1)

If I try to run create_librispeech_metadata.py directly I'm getting the following errors.
![image](https://github.com/JorisCos/LibriMix/assets/107466802/a228d9ea-2278-4cfe-b241-6830283108bd)

Thank you.

**Comment by JorisCos** [comment]
You would have to generate the metadata by yourself using `create_librimix_metadata.py`.
