### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 6: invalid start byte.

### ISSUE THREAD

**Issue by cloverhsiao** [JorisCos/LibriMix#7]
Hello,
I had an error while trying to create LibriMix. 
I am new to this area, I don't know how to fix it. Really appreciated if you can tell me where is the problem.

I had successful downloaded LibriSpeech and wham_noise.
![擷取](https://user-images.githubusercontent.com/61333088/85196732-cee13080-b30e-11ea-8872-5fcb70b44145.JPG)
![擷取2](https://user-images.githubusercontent.com/61333088/85196737-d1dc2100-b30e-11ea-88e7-92dbf7509fa1.JPG)

I used anaconda prompt to run the generate_librimix.sh and I met the following issue.

![issue](https://user-images.githubusercontent.com/61333088/85196866-c5a49380-b30f-11ea-93cf-3bf496cf3cf0.JPG)

**Comment by JorisCos** [comment]
Hello, 
Thanks for pointing out this issue. 
The problem comes from the library pysndfx.
I believe you are using Windows right ? 
I had trouble using it on my Windows machine as well but it works just fine on Linux.
I will investigate further and come back to you with more information.

**Comment by JorisCos** [comment]
I couldn't replicate the error on my machine.
Can you make sure that the output of 
` s, rate = sf.read(sound_path)
    # Get 1st channel
        s = s[:, 0]`
is a `ndarray` ?

**Comment by cloverhsiao** [comment]
Yes, I am using Window. 

`conda install -c groakat sox printf()`
solve the error caused by the library pysndfx.


 However, I got another error like this.
![sdwferf](https://user-images.githubusercontent.com/61333088/85374335-32659b00-b567-11ea-9031-a6d2d5d25512.JPG)

And I tried to run this in a Linux VirtualBox environment. 
The error reason is the same Index Error.
![ubutu](https://user-images.githubusercontent.com/61333088/85374605-9c7e4000-b567-11ea-9ded-6b847f62b2e6.JPG)


so I tried to modify the line in scripts/augment_train_noise.py
`# Get 1st channel `
`#   s = s[ : , 0 ] `
 change to 
`# Get 1st channel `
`#   s = s `

the running outcome will become like this.

![aaana](https://user-images.githubusercontent.com/61333088/85375232-9341a300-b568-11ea-8d67-56f6d5e442b4.JPG)

in Linux VirtualBox environment
![ubutu2222](https://user-images.githubusercontent.com/61333088/85375380-cdab4000-b568-11ea-9223-b9ec60880112.JPG)

**Comment by JorisCos** [comment]
You have tried to run the augmentation on wham noise multiples times.
There are 20000 noises in `wham_noise/tr` before augmentation and 60000 after augmentation.
The 20000 original noise have 2 channels the 40000 augmented have one this is why you have this error. 
Just skip augmentation IMO

**Comment by cloverhsiao** [comment]
Yes. Thank you so much. 
I successfully generate the dataset.

I find out that the program will fail if you only want to generate types mix_clean.
![mix_clean](https://user-images.githubusercontent.com/61333088/86501172-0a790180-bdc9-11ea-816d-7cf8f5a38419.JPG)
I do this at first then I always got error message.


Then I change the types to only mix_both or mix_clean + mix both and successfully generate the dataset. 

Thank you

**Comment by JorisCos** [comment]
Glad to hear that ! 
I will look into the last error thank you for reporting it ! 🚀
