### ISSUE TITLE
Running into this error when trying to generate the dataset 

### ISSUE THREAD

**Issue by ycemsubakan** [JorisCos/LibriMix#9]
![Screenshot from 2020-07-03 16-45-13](https://user-images.githubusercontent.com/17621727/86496718-9567e680-bd4c-11ea-89ac-d05931ac737c.png)

Any ideas on how to fix it? I am using conda with python 3.7. 

Thanks!

**Comment by JorisCos** [comment]
Thanks for reporting this issue.
I think you tried to run `augment_train_noise.py` multiple times.
The original sounds in wham noise tr have 2 channels the augmented one have only one.
If you have 60 000 files in wham noise tr you should skip the augmentation part.
If you don't I suggest that you start from a fresh wham noise tr folder where there are no augmented files and run the script again .

**Comment by JorisCos** [comment]
Any news @ycemsubakan ?

**Comment by ycemsubakan** [comment]
Sorry, I have decided not to use the dataset for the time being. I'll let you know if I run into issues again. But it sounded like this was an error on my side. You can close the issue. Thanks!
